/**
 * ARCADE MODE — 50 Levels
 * Each level: { id, world, name, difficulty (1-5 AI), missingPiece, hint }
 * missingPiece: which white piece the player is MISSING
 * 'Q'=Queen, 'R'=Rook, 'B'=Bishop, 'N'=Knight, 'P'=Pawn (one pawn missing)
 */

const ARCADE_WORLDS = [
  {
    id: "village",
    name: "Village",
    icon: "🏘",
    desc: "A humble beginning",
    color: "#f5a623",
    levels: [
      {
        id: 1,
        name: "Village Skirmish",
        diff: "easy",
        missing: "N",
        hint: "No knight — use your pawns wisely.",
      },
      {
        id: 2,
        name: "First Steps",
        diff: "easy",
        missing: "N",
        hint: "Both knights gone. Control the center.",
      },
      {
        id: 3,
        name: "Open Field",
        diff: "easy",
        missing: "B",
        hint: "Your bishop stayed behind.",
      },
      {
        id: 4,
        name: "Harvest Chase",
        diff: "easy",
        missing: "B",
        hint: "Fight without your dark bishop.",
      },
      {
        id: 5,
        name: "Muddy Boots",
        diff: "easy",
        missing: "P",
        hint: "One pawn short on the f-file.",
      },
      {
        id: 6,
        name: "Paddy Field",
        diff: "easy",
        missing: "P",
        hint: "The e-pawn never showed up.",
      },
      {
        id: 7,
        name: "River Crossing",
        diff: "easy",
        missing: "R",
        hint: "Your a-rook is absent.",
      },
      {
        id: 8,
        name: "Bamboo Grove",
        diff: "easy",
        missing: "R",
        hint: "Rook on h1 took a detour.",
      },
      {
        id: 9,
        name: "Dusty Road",
        diff: "easy",
        missing: "N",
        hint: "A knight errant — gone.",
      },
      {
        id: 10,
        name: "Village Square",
        diff: "easy",
        missing: "B",
        hint: "Missing a bishop. Stay sharp.",
      },
    ],
  },
  {
    id: "bazaar",
    name: "Bazaar",
    icon: "🛒",
    desc: "Deals and deception",
    color: "#e67e22",
    levels: [
      {
        id: 11,
        name: "Merchant's Row",
        diff: "easy",
        missing: "Q",
        hint: "No queen! Coordinate your pieces.",
      },
      {
        id: 12,
        name: "Spice Market",
        diff: "medium",
        missing: "N",
        hint: "Knights for trade, pawns for control.",
      },
      {
        id: 13,
        name: "Silk Road",
        diff: "medium",
        missing: "B",
        hint: "One bishop left. Use diagonals.",
      },
      {
        id: 14,
        name: "Camel Caravan",
        diff: "medium",
        missing: "P",
        hint: "The d-pawn never arrived.",
      },
      {
        id: 15,
        name: "Barter Fight",
        diff: "medium",
        missing: "R",
        hint: "Down a rook from the start.",
      },
      {
        id: 16,
        name: "Haggle Hard",
        diff: "medium",
        missing: "N",
        hint: "No knights — control with rooks.",
      },
      {
        id: 17,
        name: "Narrow Alley",
        diff: "medium",
        missing: "B",
        hint: "Bishops don't fit in alleys.",
      },
      {
        id: 18,
        name: "Coin Toss",
        diff: "medium",
        missing: "R",
        hint: "Trade a rook for a win.",
      },
      {
        id: 19,
        name: "Night Market",
        diff: "medium",
        missing: "P",
        hint: "c-pawn missing at midnight.",
      },
      {
        id: 20,
        name: "Bazaar Champion",
        diff: "medium",
        missing: "Q",
        hint: "No queen — win on pure tactics.",
      },
    ],
  },
  {
    id: "palace",
    name: "Palace",
    icon: "🏯",
    desc: "Royal courts, royal rules",
    color: "#8e44ad",
    levels: [
      {
        id: 21,
        name: "Palace Gates",
        diff: "medium",
        missing: "Q",
        hint: "The queen is imprisoned. Fight on.",
      },
      {
        id: 22,
        name: "Throne Room",
        diff: "medium",
        missing: "R",
        hint: "No rook on the queenside.",
      },
      {
        id: 23,
        name: "Court Jester",
        diff: "medium",
        missing: "N",
        hint: "Knights demoted. Use bishops.",
      },
      {
        id: 24,
        name: "Royal Guard",
        diff: "hard",
        missing: "B",
        hint: "One bishop assigned elsewhere.",
      },
      {
        id: 25,
        name: "Banquet Hall",
        diff: "hard",
        missing: "P",
        hint: "The b-pawn skipped the feast.",
      },
      {
        id: 26,
        name: "Dungeon Escape",
        diff: "hard",
        missing: "R",
        hint: "Your h-rook locked in the dungeon.",
      },
      {
        id: 27,
        name: "Tower Defense",
        diff: "hard",
        missing: "Q",
        hint: "Without a queen, defend and attack.",
      },
      {
        id: 28,
        name: "Grand Vizier",
        diff: "hard",
        missing: "N",
        hint: "No knights in royal chambers.",
      },
      {
        id: 29,
        name: "Palace Intrigue",
        diff: "hard",
        missing: "B",
        hint: "A bishop lost to palace politics.",
      },
      {
        id: 30,
        name: "Palace Champion",
        diff: "hard",
        missing: "R",
        hint: "Defeat the palace guard without a rook.",
      },
    ],
  },
  {
    id: "fortress",
    name: "Fortress",
    icon: "🏰",
    desc: "Walls of iron, tests of will",
    color: "#c0392b",
    levels: [
      {
        id: 31,
        name: "Siege Begins",
        diff: "hard",
        missing: "Q",
        hint: "Queen at the siege camp. You're alone.",
      },
      {
        id: 32,
        name: "Battering Ram",
        diff: "hard",
        missing: "R",
        hint: "No rooks for battering walls.",
      },
      {
        id: 33,
        name: "Moat Crossing",
        diff: "hard",
        missing: "N",
        hint: "Knights can't jump the moat.",
      },
      {
        id: 34,
        name: "Arrow Barrage",
        diff: "hard",
        missing: "P",
        hint: "g-pawn fell to an arrow.",
      },
      {
        id: 35,
        name: "Wall Breach",
        diff: "hard",
        missing: "B",
        hint: "One bishop fell at the walls.",
      },
      {
        id: 36,
        name: "Inner Courtyard",
        diff: "hard",
        missing: "Q",
        hint: "The queen breached another wall.",
      },
      {
        id: 37,
        name: "War Room",
        diff: "hard",
        missing: "R",
        hint: "Rooks too heavy for the war room.",
      },
      {
        id: 38,
        name: "Siege Tower",
        diff: "hard",
        missing: "N",
        hint: "No knights in the tower.",
      },
      {
        id: 39,
        name: "Keep Assault",
        diff: "hard",
        missing: "B",
        hint: "Bishops can't scale the keep.",
      },
      {
        id: 40,
        name: "Fortress Champion",
        diff: "hard",
        missing: "Q",
        hint: "Storm the fortress without a queen.",
      },
    ],
  },
  {
    id: "legend",
    name: "Legend",
    icon: "⚔️",
    desc: "Only legends survive this",
    color: "#d4af37",
    levels: [
      {
        id: 41,
        name: "The Gauntlet",
        diff: "hard",
        missing: "Q",
        hint: "No queen. No mercy.",
      },
      {
        id: 42,
        name: "Shadow Realm",
        diff: "hard",
        missing: "R",
        hint: "Two rooks locked in shadow.",
      },
      {
        id: 43,
        name: "Dragon's Pass",
        diff: "hard",
        missing: "B",
        hint: "Bishops fear the dragon.",
      },
      {
        id: 44,
        name: "Ancient Grudge",
        diff: "hard",
        missing: "N",
        hint: "No knights in ancient tales.",
      },
      {
        id: 45,
        name: "Forsaken Queen",
        diff: "hard",
        missing: "Q",
        hint: "The queen has forsaken you.",
      },
      {
        id: 46,
        name: "Last Stand",
        diff: "hard",
        missing: "R",
        hint: "Your rooks fell. Fight on.",
      },
      {
        id: 47,
        name: "Endgame Prophecy",
        diff: "hard",
        missing: "N",
        hint: "Prophets have no use for knights.",
      },
      {
        id: 48,
        name: "Eternal Battle",
        diff: "hard",
        missing: "B",
        hint: "Your bishop walks another path.",
      },
      {
        id: 49,
        name: "Champion's Trial",
        diff: "hard",
        missing: "Q",
        hint: "A true champion needs no queen.",
      },
      {
        id: 50,
        name: "True Legend",
        diff: "hard",
        missing: "Q",
        hint: "Win it all — no queen, full glory.",
      },
    ],
  },
];

// Flatten for easy access
const ALL_LEVELS = ARCADE_WORLDS.flatMap((w) =>
  w.levels.map((l) => ({
    ...l,
    world: w.id,
    worldName: w.name,
    worldColor: w.color,
  })),
);

module.exports = { ARCADE_WORLDS, ALL_LEVELS };
